version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: reinvent-trivia-backend

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y jq
      - npm install -g npm@6.4.1

  pre_build:
    commands:
      # Set up environment variables like image tag and repo
      - cd $CODEBUILD_SRC_DIR/trivia-backend
      - export IMAGE_TAG=build-`echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}'`
      - AWS_ACCOUNT_ID=`echo $CODEBUILD_BUILD_ARN | awk -F":" '{print $5}'`
      - ECR_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - $(aws ecr get-login --no-include-email)

      # Consume base image
      - export BASE_IMAGE=`jq -r '.ImageURI' <$CODEBUILD_SRC_DIR_BaseImage/imageDetail.json`
      - sed -i "s|reinvent-trivia-backend-base:release|$BASE_IMAGE|g" Dockerfile

  build:
    commands:
      # Build Docker image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:$IMAGE_TAG

      # Save the Docker image digest
      - IMAGE_URI=`docker inspect --format='{{index .RepoDigests 0}}' $ECR_REPO:$IMAGE_TAG`
      - echo Built image $IMAGE_URI, pushed with tag $IMAGE_TAG
      - echo "{\"ImageURI\":\"$IMAGE_URI\"}" > imageDetail.json

      # Add subnet and security group info to appspec
      - cd blue-green-setup
      - mkdir build
      - npm ci
      - node produce-config.js -g test -s TriviaBackendTest -h TriviaBackendHooksTest
      - node produce-config.js -g prod -s TriviaBackendProd -h TriviaBackendHooksProd
      - cp task-definition.json build/
      - sed -i "s/123456789012/$AWS_ACCOUNT_ID/g" build/*

artifacts:
  secondary-artifacts:
    BuildArtifact:
      files:
        - trivia-backend/blue-green-setup/build/appspec-prod.json
        - trivia-backend/blue-green-setup/build/appspec-test.json
        - trivia-backend/blue-green-setup/build/task-definition.json
      discard-paths: yes
    ImageDetails:
      files:
        - trivia-backend/imageDetail.json
      discard-paths: yes
