version: 0.2

env:
  variables:
    STAGE: "dev"
    WEBSITE_BUCKET: ""

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y jq
      - npm install -g npm@6.4.1
      - cd static-site/app
      - chmod +x deploy-to-bucket.sh
      - npm ci
  build:
    commands:
      - npm run build:$STAGE
      - cp index.html build/
      - cp -rf assets build/
      - cd build/
      - ../deploy-to-bucket.sh
